### ISSUE TITLE
Blinkin on each state update

### ISSUE THREAD

**Issue by RamiRihawi** [swingerman/lovelace-fluid-level-background-card#480]
I am using Version 0.1.8.2

As the title said, on every sensor state update the card blink.

**Comment by ildar170975** [comment]
Post a code of your card.

**Comment by ildar170975** [comment]
1. The posted code is unformatted. Place a code into triple "`". Actually, you could have noticed yourself that the code has no indents. If you wish to get a help, you need to provide data in a proper way.
2. Do you have any other cards ABOVE the `fluid-level-background-card` card? I am asking because some users use template-supported cards like `config-template-card on a higher level & do not mention it.`

**Comment by swingerman** [comment]
Possibly fixed by #483

**Comment by Protoncek** [comment]
Hello!
I just discovered this (wonderful) card, but... is this really fixed? My card still blinks at each value change...
